<html>
    <head>
        
        <script src= "<?php echo $this->baseUrl() ?>/jq/JQuery%20Source/jquery-1.11.2.js"></script>
<script src="<?php echo $this->baseUrl() ?>/jq/jquery-ui-1.11.4.custom/jquery-ui.js"></script>
<link href="<?php echo $this->baseUrl() ?>/jq/jquery-ui-1.11.4.custom/jquery-ui.css" rel="stylesheet" />
        <script src="<?php echo $this->baseUrl();?>/jq/checks.js" type="text/javascript"></script>

    </head>
    <body>
        <div id="view-content">
            
            
            <?php echo $this->form; ?>
        
        
        </div>
        <div id="datetotal"></div>
    </body>
</html>
