<!DOCTYPE html>
<html>
   
    <body border="1">
        <div id="header">
            <p>Cafeteria</p>
        </div>
        <div id="main">
            <div id="loginform" align="center" cellspacing="30px">
              
                            <?php
                            echo $this->form;
                            ?>
                         
            </div>		
        </div>
        
    </body>

</html>
