<html>
    <head>
        
         <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/login.css"/>
    </head>
    <body>
    
                        <div  style="float:right; margin: 56px 72px 102px 331px;">
                            <?php
                            $z=Zend_Auth::getInstance();
       
                            $user_name = $z->getIdentity()->user_name;
                            
                            $user_image = $z->getIdentity()->user_image ;
        
                            ?>
                            <img  width="50" height="50" src="<?php echo $this->baseUrl("images/".$user_image)  ?>"/>
                            <a ><?php echo $user_name ?></a>
                            <a href="<?php echo $this->baseUrl();?>/user/logout/">Logout</a>    
                                
                                
			</div> 
        
    
 <div style="float:right; margin:-31px -172px 29px 381px;" > <a  href="<?php echo $this->baseUrl()?>/user/signup">Add New User</a> </div>    
        <div >
            <table style="  margin: 167px 47px 97px 339px;">
    <tr>
        <th colspan="6"><center>All Users</center></th>
    </tr>     

    <tr>
        <th>Name</th>
        <th>Room</th>
        <th>Image</th>
        <th>Ext.</th>
        <th colspan="2">Action</td>
    </tr>      

   
<?php 

   foreach ($this->paginator as $user)
   {
       ?>
    
      
        <?php
        echo "<tr>";
        echo "<td>".$user['user_name']."</td>";
        echo "<td>".$user['room_no']."</td>";
        echo "<td ><img width='50' height='50' src='".$this->baseUrl("images/".$user['user_image'])."' /></td>";
        echo "<td>".$user['extension']."</td>";
        echo "<td ><a href='".$this->baseUrl()."/user/edit/id/".$user['id']."'>Edit</a></td>";
        echo "<td><a href='".$this->baseUrl()."/user/delete/id/".$user['id']."'> Delete</a></td>";
        echo "</tr>";  
    
    ?>
   
       
<?php
   }
   
?>
    <?php
   
  echo  $this->paginationControl($this->paginator,'Sliding','pagination.phtml')
?>   
 </table>
    </div>
   
    </body>
</html>
  
