<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/login.css"/>
    </head>
    <body>
        <div class="container">
           
	<section id="content">
            
			
                            <?php
                            echo $this->form;
                            ?>
                        <a  href="<?php echo $this->baseUrl() ?>/user/forgetpassword/">Forget Password?</a>
                       
   
          
                                    
</section>
                 </div>
    </body>
     

</html>
	